apiVersion: v1
# Local secret for database credentials, replace with your own values into file secret-db.yaml
kind: Secret
metadata:
  name: db-credentials
  namespace: spring-data-rest
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://host:3306/dbname
  SPRING_DATASOURCE_USERNAME: 
  SPRING_DATASOURCE_PASSWORD: 