apiVersion: v1
kind: Service
metadata:
  name: spring-data-rest
  namespace: spring-data-rest
  labels:
    app: spring-data-rest
spec:
  type: ClusterIP
  selector:
    app: spring-data-rest
  ports:
    - name: http
      port: 80
      targetPort: 8080