CREATE TABLE backtest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method VARCHAR(20) NOT NULL,
    asset VARCHAR(5) NOT NULL,
    currency VARCHAR(5) NOT NULL,
    datefrom BIGINT NOT NULL,
    dateto BIGINT NOT NULL,
    confighash VARCHAR(255) NOT NULL,
    config CLOB NOT NULL,
    backtest CLOB NOT NULL,
    performance CLOB NOT NULL,
    CONSTRAINT uk_backtest_method_asset_currency_date_confighash
        UNIQUE (method, asset, currency, datefrom, dateto, confighash)
);

